import type { AppConfig, ProviderConfig } from './types';
import { CONFIG_SCHEMA_VERSION } from './types';

/** Built-in provider instances, one per supported backend. */
export const DEFAULT_PROVIDERS: ProviderConfig[] = [
  {
    id: 'hunyuan',
    name: '混元 (Hunyuan)',
    provider: 'hunyuan',
    apiKey: '',
    baseURL: 'http://hunyuanapi.woa.com/openapi/v1',
    model: 'hunyuan-turbos-latest',
    enabled: true,
  },
  {
    id: 'taiji',
    name: '太极 (Taiji)',
    provider: 'taiji',
    apiKey: '',
    baseURL: 'http://api.taiji.woa.com/openapi/v2',
    model: 'hunyuan-translation-pro',
    enabled: true,
  },
  {
    id: 'fat',
    name: 'FAT (公司 AI 网关)',
    provider: 'fat',
    apiKey: '',
    baseURL: 'http://dev.fit-ai.woa.com/api/llmproxy',
    model: 'deepseek-v3.1',
    enabled: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    provider: 'deepseek',
    apiKey: '',
    baseURL: 'https://api.deepseek.com',
    model: 'deepseek-chat',
    enabled: true,
  },
];

export const DEFAULT_CONFIG: AppConfig = {
  schemaVersion: CONFIG_SCHEMA_VERSION,
  general: {
    uiLanguage: 'auto',
    sourceLang: 'auto',
    targetLang: 'zh-Hans',
    level: 'intermediate',
  },
  providersConfig: DEFAULT_PROVIDERS,
  customActions: [
    {
      id: 'explain',
      name: '解释',
      icon: '💡',
      providerId: 'hunyuan',
      prompt:
        '你是一名语言老师。请用简洁的{{targetLang}}解释下面这段文字的含义、语气与难点：\n\n{{text}}',
      enabled: true,
    },
    {
      id: 'summarize',
      name: '总结',
      icon: '📝',
      providerId: 'hunyuan',
      prompt: '请用{{targetLang}}对下面内容做要点总结：\n\n{{text}}',
      enabled: true,
    },
  ],
  translate: {
    providerId: 'hunyuan',
    mode: 'bilingual',
    showOriginalOnHover: true,
    node: {
      enabled: true,
      hotkey: 'alt',
    },
    page: {
      range: 'main',
      autoTranslatePatterns: [],
      neverAutoTranslatePatterns: ['*.google.com/*', 'localhost'],
      minWordsPerNode: 1,
    },
    enableAIContentAware: true,
    // 预置多领域术语表（每行「原词 : 译词」，# 开头为分组注释，不参与匹配）。
    // 结构化 references 仅取前 10 条，其余经 context 全文注入（见 woa.ts）。
    glossary: [
      '# 计算机',
      'computer science : 计算机科学',
      'algorithm : 算法',
      'runtime : 运行时',
      'compiler : 编译器',
      'kernel : 内核',
      'recursion : 递归',
      '# AI',
      'artificial intelligence : 人工智能',
      'machine learning : 机器学习',
      'large language model : 大语言模型',
      'neural network : 神经网络',
      'inference : 推理',
      'fine-tuning : 微调',
      'agent : 智能体',
      'hallucination : 幻觉',
      '# 金融',
      'stock : 股票',
      'bond : 债券',
      'interest rate : 利率',
      'market capitalization : 市值',
      'liquidity : 流动性',
      'quantitative easing : 量化宽松',
      'bull market : 牛市',
      'bear market : 熊市',
      '# 游戏',
      'game engine : 游戏引擎',
      'NPC : 非玩家角色',
      'frame rate : 帧率',
      'respawn : 重生',
      'hitbox : 判定框',
      'battle royale : 大逃杀',
      'DLC : 可下载内容',
      '# 政治',
      'election : 选举',
      'legislation : 立法',
      'bipartisan : 两党的',
      'referendum : 全民公投',
      'sanction : 制裁',
      'veto : 否决权',
      '# 半导体科技',
      'semiconductor : 半导体',
      'wafer : 晶圆',
      'lithography : 光刻',
      'transistor : 晶体管',
      'process node : 制程节点',
      'EUV : 极紫外光刻',
      'fab : 晶圆厂',
      '# 医学',
      'clinical trial : 临床试验',
      'placebo : 安慰剂',
      'diagnosis : 诊断',
      'prognosis : 预后',
      'inflammation : 炎症',
      'antibiotic : 抗生素',
      '# 法律',
      'lawsuit : 诉讼',
      'plaintiff : 原告',
      'defendant : 被告',
      'jurisdiction : 管辖权',
      'liability : 法律责任',
      'statute : 成文法',
      'precedent : 判例',
    ].join('\n'),
    customPrompt: '',
    requestQueue: {
      capacity: 5,
      rate: 5,
    },
    batchQueue: {
      maxCharactersPerBatch: 2000,
      maxItemsPerBatch: 20,
    },
    nodeStyle: {
      preset: 'dashed',
      customCSS: null,
    },
  },
  siteRules: {
    mode: 'blacklist',
    blacklistPatterns: [],
    whitelistPatterns: [],
  },
  videoSubtitles: {
    enabled: false,
    autoStart: false,
    providerId: 'hunyuan',
    style: {
      displayMode: 'bilingual',
      translationPosition: 'bottom',
      main: { fontScale: 1, color: '#ffffff', fontWeight: 400 },
      translation: { fontScale: 1, color: '#ffd54f', fontWeight: 500 },
      backgroundOpacity: 0.5,
    },
  },
  inputTranslation: {
    enabled: false,
    providerId: 'hunyuan',
    fromLang: 'auto',
    toLang: 'targetCode',
    enableCycle: false,
    timeThreshold: 500,
    triggerKey: '3xSpace',
  },
  selection: {
    providerId: 'hunyuan',
    enabled: true,
    disabledPatterns: [],
  },
  floatingButton: {
    enabled: true,
    position: 0.66,
    side: 'right',
    clickAction: 'translate',
    locked: false,
    disabledPatterns: [],
  },
  languageDetection: {
    mode: 'basic',
    providerId: 'hunyuan',
  },
  tts: {
    enabled: false,
    voiceURI: '',
    rate: 1,
    pitch: 1,
    volume: 1,
    langMode: 'auto',
    customLang: 'zh-CN',
  },
  contextMenu: {
    enabled: true,
  },
};
