import type { AppConfig, ProviderConfig } from './types';
import { CONFIG_SCHEMA_VERSION } from './types';

/** Built-in provider instances, one per supported backend. */
export const DEFAULT_PROVIDERS: ProviderConfig[] = [
  {
    id: 'hunyuan',
    name: '混元 (Hunyuan)',
    provider: 'hunyuan',
    apiKey: '',
    baseURL: 'http://hunyuanapi.woa.com/openapi/v1',
    model: 'hunyuan-turbos-latest',
    enabled: true,
  },
  {
    id: 'taiji',
    name: '太极 (Taiji)',
    provider: 'taiji',
    apiKey: '',
    baseURL: 'http://api.taiji.woa.com/openapi/v2',
    model: 'hunyuan-translation-pro',
    enabled: true,
  },
  {
    id: 'fat',
    name: 'FAT (公司 AI 网关)',
    provider: 'fat',
    apiKey: '',
    baseURL: 'http://dev.fit-ai.woa.com/api/llmproxy',
    model: 'deepseek-v3.1',
    enabled: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    provider: 'deepseek',
    apiKey: '',
    baseURL: 'https://api.deepseek.com',
    model: 'deepseek-chat',
    enabled: true,
  },
];

export const DEFAULT_CONFIG: AppConfig = {
  schemaVersion: CONFIG_SCHEMA_VERSION,
  general: {
    uiLanguage: 'auto',
    sourceLang: 'auto',
    targetLang: 'zh-Hans',
    level: 'intermediate',
  },
  providersConfig: DEFAULT_PROVIDERS,
  customActions: [
    {
      id: 'explain',
      name: '解释',
      icon: '💡',
      providerId: 'hunyuan',
      prompt:
        '你是一名语言老师。请用简洁的{{targetLang}}解释下面这段文字的含义、语气与难点：\n\n{{text}}',
      enabled: true,
    },
    {
      id: 'summarize',
      name: '总结',
      icon: '📝',
      providerId: 'hunyuan',
      prompt: '请用{{targetLang}}对下面内容做要点总结：\n\n{{text}}',
      enabled: true,
    },
  ],
  translate: {
    providerId: 'hunyuan',
    mode: 'bilingual',
    showOriginalOnHover: true,
    node: {
      enabled: true,
      hotkey: 'alt',
    },
    page: {
      range: 'main',
      autoTranslatePatterns: [],
      neverAutoTranslatePatterns: ['*.google.com/*', 'localhost'],
      minWordsPerNode: 1,
    },
    enableAIContentAware: true,
    // 预置 8 大领域术语表（每行「原词 : 译词」，# 开头为分组注释，不参与匹配）。
    // 结构化 references 仅取前 10 条，全部术语同时经 context 全文注入（见 woa.ts）。
    glossary: [
      '# 计算机',
      'computer science : 计算机科学',
      'algorithm : 算法',
      'data structure : 数据结构',
      'runtime : 运行时',
      'compiler : 编译器',
      'interpreter : 解释器',
      'kernel : 内核',
      'recursion : 递归',
      'concurrency : 并发',
      'parallelism : 并行',
      'asynchronous : 异步',
      'synchronous : 同步',
      'cache : 缓存',
      'database : 数据库',
      'index : 索引',
      'framework : 框架',
      'library : 库',
      'dependency : 依赖',
      'deployment : 部署',
      'container : 容器',
      'virtual machine : 虚拟机',
      'cloud computing : 云计算',
      'serverless : 无服务器',
      'microservices : 微服务',
      'API : 应用程序接口',
      'SDK : 软件开发工具包',
      'IDE : 集成开发环境',
      'debugging : 调试',
      'refactoring : 重构',
      'version control : 版本控制',
      'repository : 代码仓库',
      'pull request : 拉取请求',
      'open source : 开源',
      'encryption : 加密',
      'authentication : 身份验证',
      'authorization : 授权',
      'firewall : 防火墙',
      'bandwidth : 带宽',
      'latency : 延迟',
      'throughput : 吞吐量',
      '# AI',
      'artificial intelligence : 人工智能',
      'machine learning : 机器学习',
      'deep learning : 深度学习',
      'large language model : 大语言模型',
      'neural network : 神经网络',
      'inference : 推理',
      'training : 训练',
      'fine-tuning : 微调',
      'pre-training : 预训练',
      'agent : 智能体',
      'hallucination : 幻觉',
      'prompt : 提示词',
      'prompt engineering : 提示工程',
      'token : 词元',
      'embedding : 嵌入',
      'vector : 向量',
      'attention mechanism : 注意力机制',
      'parameter : 参数',
      'model weights : 模型权重',
      'gradient descent : 梯度下降',
      'backpropagation : 反向传播',
      'overfitting : 过拟合',
      'underfitting : 欠拟合',
      'supervised learning : 监督学习',
      'unsupervised learning : 无监督学习',
      'reinforcement learning : 强化学习',
      'RLHF : 人类反馈强化学习',
      'generative AI : 生成式人工智能',
      'diffusion model : 扩散模型',
      'multimodal : 多模态',
      'computer vision : 计算机视觉',
      'natural language processing : 自然语言处理',
      'speech recognition : 语音识别',
      'text-to-speech : 文本转语音',
      'retrieval-augmented generation : 检索增强生成',
      'chain-of-thought : 思维链',
      'context window : 上下文窗口',
      'quantization : 量化',
      'foundation model : 基础模型',
      'transformer : Transformer 架构',
      '# 金融',
      'stock : 股票',
      'bond : 债券',
      'equity : 股权',
      'interest rate : 利率',
      'market capitalization : 市值',
      'liquidity : 流动性',
      'quantitative easing : 量化宽松',
      'bull market : 牛市',
      'bear market : 熊市',
      'inflation : 通货膨胀',
      'deflation : 通货紧缩',
      'recession : 经济衰退',
      'GDP : 国内生产总值',
      'dividend : 股息',
      'portfolio : 投资组合',
      'asset : 资产',
      'liability : 负债',
      'hedge fund : 对冲基金',
      'mutual fund : 共同基金',
      'ETF : 交易型开放式指数基金',
      'IPO : 首次公开募股',
      'volatility : 波动率',
      'yield : 收益率',
      'leverage : 杠杆',
      'margin : 保证金',
      'derivative : 衍生品',
      'futures : 期货',
      'options : 期权',
      'arbitrage : 套利',
      'bankruptcy : 破产',
      'credit rating : 信用评级',
      'fiscal policy : 财政政策',
      'monetary policy : 货币政策',
      'central bank : 中央银行',
      'Federal Reserve : 美联储',
      'treasury : 国债',
      'foreign exchange : 外汇',
      'cryptocurrency : 加密货币',
      'blockchain : 区块链',
      'asset allocation : 资产配置',
      '# 游戏',
      'game engine : 游戏引擎',
      'NPC : 非玩家角色',
      'frame rate : 帧率',
      'respawn : 重生',
      'hitbox : 判定框',
      'battle royale : 大逃杀',
      'DLC : 可下载内容',
      'RPG : 角色扮演游戏',
      'FPS : 第一人称射击游戏',
      'MMORPG : 大型多人在线角色扮演游戏',
      'MOBA : 多人在线战术竞技游戏',
      'sandbox : 沙盒',
      'open world : 开放世界',
      'quest : 任务',
      'level up : 升级',
      'experience points : 经验值',
      'skill tree : 技能树',
      'cooldown : 冷却时间',
      'buff : 增益效果',
      'debuff : 减益效果',
      'loot : 战利品',
      'crafting : 合成',
      'multiplayer : 多人游戏',
      'single-player : 单人游戏',
      'co-op : 合作模式',
      'PvP : 玩家对战',
      'PvE : 玩家对环境',
      'esports : 电子竞技',
      'streaming : 直播',
      'mod : 模组',
      'patch : 补丁',
      'nerf : 削弱',
      'glitch : 游戏漏洞',
      'speedrun : 速通',
      'achievement : 成就',
      'leaderboard : 排行榜',
      'matchmaking : 匹配系统',
      'ray tracing : 光线追踪',
      'lag : 卡顿',
      'ping : 网络延迟',
      '# 政治',
      'election : 选举',
      'legislation : 立法',
      'bipartisan : 两党的',
      'referendum : 全民公投',
      'sanction : 制裁',
      'veto : 否决权',
      'democracy : 民主',
      'constitution : 宪法',
      'amendment : 修正案',
      'parliament : 议会',
      'congress : 国会',
      'senate : 参议院',
      'House of Representatives : 众议院',
      'impeachment : 弹劾',
      'diplomacy : 外交',
      'treaty : 条约',
      'summit : 峰会',
      'campaign : 竞选活动',
      'ballot : 选票',
      'voter turnout : 投票率',
      'polling : 民意调查',
      'incumbent : 现任者',
      'opposition : 反对派',
      'coalition : 联合政府',
      'cabinet : 内阁',
      'bureaucracy : 官僚机构',
      'lobby : 游说',
      'censorship : 审查制度',
      'sovereignty : 主权',
      'geopolitics : 地缘政治',
      'tariff : 关税',
      'embargo : 禁运',
      'asylum : 庇护',
      'refugee : 难民',
      'human rights : 人权',
      'civil liberties : 公民自由',
      'populism : 民粹主义',
      'nationalism : 民族主义',
      'ideology : 意识形态',
      'propaganda : 宣传',
      '# 半导体科技',
      'semiconductor : 半导体',
      'wafer : 晶圆',
      'lithography : 光刻',
      'transistor : 晶体管',
      'process node : 制程节点',
      'EUV : 极紫外光刻',
      'fab : 晶圆厂',
      'chip : 芯片',
      'integrated circuit : 集成电路',
      'CPU : 中央处理器',
      'GPU : 图形处理器',
      'SoC : 片上系统',
      'DRAM : 动态随机存取存储器',
      'NAND flash : NAND 闪存',
      "Moore's Law : 摩尔定律",
      'yield rate : 良率',
      'doping : 掺杂',
      'etching : 蚀刻',
      'deposition : 沉积',
      'packaging : 封装',
      'foundry : 代工厂',
      'fabless : 无晶圆厂',
      'photomask : 光掩模',
      'silicon : 硅',
      'substrate : 衬底',
      'interconnect : 互连',
      'die : 裸片',
      'nanometer : 纳米',
      'FinFET : 鳍式场效应晶体管',
      'bandgap : 带隙',
      'cleanroom : 洁净室',
      'fabrication : 制造',
      'supply chain : 供应链',
      'export control : 出口管制',
      'advanced packaging : 先进封装',
      'chiplet : 小芯片',
      'photolithography : 光刻技术',
      'yield : 良品率',
      'doping concentration : 掺杂浓度',
      '# 医学',
      'clinical trial : 临床试验',
      'placebo : 安慰剂',
      'diagnosis : 诊断',
      'prognosis : 预后',
      'inflammation : 炎症',
      'antibiotic : 抗生素',
      'vaccine : 疫苗',
      'symptom : 症状',
      'syndrome : 综合征',
      'chronic : 慢性的',
      'acute : 急性的',
      'benign : 良性的',
      'malignant : 恶性的',
      'tumor : 肿瘤',
      'cancer : 癌症',
      'chemotherapy : 化疗',
      'radiation therapy : 放疗',
      'surgery : 外科手术',
      'anesthesia : 麻醉',
      'immunity : 免疫力',
      'antibody : 抗体',
      'antigen : 抗原',
      'virus : 病毒',
      'bacteria : 细菌',
      'infection : 感染',
      'epidemic : 流行病',
      'pandemic : 大流行病',
      'quarantine : 隔离',
      'prescription : 处方',
      'dosage : 剂量',
      'side effect : 副作用',
      'therapy : 治疗',
      'rehabilitation : 康复',
      'gene : 基因',
      'DNA : 脱氧核糖核酸',
      'RNA : 核糖核酸',
      'protein : 蛋白质',
      'metabolism : 新陈代谢',
      'cardiovascular : 心血管的',
      'immune system : 免疫系统',
      '# 法律',
      'lawsuit : 诉讼',
      'plaintiff : 原告',
      'defendant : 被告',
      'jurisdiction : 管辖权',
      'liability : 法律责任',
      'statute : 成文法',
      'precedent : 判例',
      'contract : 合同',
      'tort : 侵权',
      'negligence : 过失',
      'damages : 损害赔偿',
      'settlement : 和解',
      'verdict : 裁决',
      'testimony : 证词',
      'witness : 证人',
      'evidence : 证据',
      'prosecutor : 检察官',
      'defense attorney : 辩护律师',
      'judge : 法官',
      'jury : 陪审团',
      'appeal : 上诉',
      'Supreme Court : 最高法院',
      'constitutional law : 宪法',
      'criminal law : 刑法',
      'civil law : 民法',
      'intellectual property : 知识产权',
      'patent : 专利',
      'trademark : 商标',
      'copyright : 版权',
      'arbitration : 仲裁',
      'mediation : 调解',
      'injunction : 禁令',
      'subpoena : 传票',
      'indictment : 起诉书',
      'felony : 重罪',
      'misdemeanor : 轻罪',
      'bail : 保释',
      'parole : 假释',
      'due process : 正当程序',
      'litigation : 诉讼程序',
    ].join('\n'),
    customPrompt: '',
    requestQueue: {
      capacity: 5,
      rate: 5,
    },
    batchQueue: {
      maxCharactersPerBatch: 2000,
      maxItemsPerBatch: 20,
    },
    nodeStyle: {
      preset: 'dashed',
      customCSS: null,
    },
  },
  siteRules: {
    mode: 'blacklist',
    blacklistPatterns: [],
    whitelistPatterns: [],
  },
  videoSubtitles: {
    enabled: false,
    autoStart: false,
    providerId: 'hunyuan',
    style: {
      displayMode: 'bilingual',
      translationPosition: 'bottom',
      main: { fontScale: 1, color: '#ffffff', fontWeight: 400 },
      translation: { fontScale: 1, color: '#ffd54f', fontWeight: 500 },
      backgroundOpacity: 0.5,
    },
  },
  inputTranslation: {
    enabled: false,
    providerId: 'hunyuan',
    fromLang: 'auto',
    toLang: 'targetCode',
    enableCycle: false,
    timeThreshold: 500,
    triggerKey: '3xSpace',
  },
  selection: {
    providerId: 'hunyuan',
    enabled: true,
    disabledPatterns: [],
  },
  floatingButton: {
    enabled: true,
    position: 0.66,
    side: 'right',
    clickAction: 'translate',
    locked: false,
    disabledPatterns: [],
  },
  languageDetection: {
    mode: 'basic',
    providerId: 'hunyuan',
  },
  tts: {
    enabled: false,
    voiceURI: '',
    rate: 1,
    pitch: 1,
    volume: 1,
    langMode: 'auto',
    customLang: 'zh-CN',
  },
  contextMenu: {
    enabled: true,
  },
};
